// <auto-generated />
using System;
using Closify.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Closify.Migrations
{
    [DbContext(typeof(ClosifyContext))]
    [Migration("20181006124641_Corev1.2")]
    partial class Corev12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Closify.Models.Acabamento", b =>
                {
                    b.Property<int>("AcabamentoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("AcabamentoID");

                    b.ToTable("Acabamentos");
                });

            modelBuilder.Entity("Closify.Models.Dimensao", b =>
                {
                    b.Property<int>("DimensaoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TipoValorAltura");

                    b.Property<int>("TipoValorComprimento");

                    b.Property<int>("TipoValorLargura");

                    b.HasKey("DimensaoID");

                    b.ToTable("Dimensao");
                });

            modelBuilder.Entity("Closify.Models.ItemDeProduto", b =>
                {
                    b.Property<int>("ItemDeProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProdutoBaseProdutoID");

                    b.Property<int?>("ProdutoParteProdutoID");

                    b.HasKey("ItemDeProdutoID");

                    b.HasIndex("ProdutoBaseProdutoID");

                    b.HasIndex("ProdutoParteProdutoID");

                    b.ToTable("ItemsDeProduto");
                });

            modelBuilder.Entity("Closify.Models.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("MaterialID");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("Closify.Models.MaterialAcabemento", b =>
                {
                    b.Property<int>("MaterialAcabementoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AcabamentoID");

                    b.Property<int?>("MaterialID");

                    b.HasKey("MaterialAcabementoID");

                    b.HasIndex("AcabamentoID");

                    b.HasIndex("MaterialID");

                    b.ToTable("MaterialAcabemento");
                });

            modelBuilder.Entity("Closify.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DimensaoID");

                    b.Property<int?>("MaterialAcabementoID");

                    b.HasKey("ProdutoID");

                    b.HasIndex("DimensaoID");

                    b.HasIndex("MaterialAcabementoID");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Closify.Models.Restricao", b =>
                {
                    b.Property<int>("RestricaoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("ItemDeProdutoID");

                    b.Property<string>("NomeRestricao");

                    b.HasKey("RestricaoID");

                    b.HasIndex("ItemDeProdutoID");

                    b.ToTable("Restricao");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Restricao");
                });

            modelBuilder.Entity("Closify.Models.ValorNumerico", b =>
                {
                    b.Property<int>("ValorNumericoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DimensaoID");

                    b.Property<int?>("DimensaoID1");

                    b.Property<int?>("DimensaoID2");

                    b.Property<double>("Valor");

                    b.HasKey("ValorNumericoID");

                    b.HasIndex("DimensaoID");

                    b.HasIndex("DimensaoID1");

                    b.HasIndex("DimensaoID2");

                    b.ToTable("ValorNumerico");
                });

            modelBuilder.Entity("Closify.Models.RestricaoDimensao", b =>
                {
                    b.HasBaseType("Closify.Models.Restricao");


                    b.ToTable("RestricaoDimensao");

                    b.HasDiscriminator().HasValue("RestricaoDimensao");
                });

            modelBuilder.Entity("Closify.Models.ItemDeProduto", b =>
                {
                    b.HasOne("Closify.Models.Produto", "ProdutoBase")
                        .WithMany("ItemsDeProdutos")
                        .HasForeignKey("ProdutoBaseProdutoID");

                    b.HasOne("Closify.Models.Produto", "ProdutoParte")
                        .WithMany()
                        .HasForeignKey("ProdutoParteProdutoID");
                });

            modelBuilder.Entity("Closify.Models.MaterialAcabemento", b =>
                {
                    b.HasOne("Closify.Models.Acabamento", "Acabamento")
                        .WithMany()
                        .HasForeignKey("AcabamentoID");

                    b.HasOne("Closify.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID");
                });

            modelBuilder.Entity("Closify.Models.Produto", b =>
                {
                    b.HasOne("Closify.Models.Dimensao", "Dimensao")
                        .WithMany()
                        .HasForeignKey("DimensaoID");

                    b.HasOne("Closify.Models.MaterialAcabemento", "MaterialAcabemento")
                        .WithMany()
                        .HasForeignKey("MaterialAcabementoID");
                });

            modelBuilder.Entity("Closify.Models.Restricao", b =>
                {
                    b.HasOne("Closify.Models.ItemDeProduto")
                        .WithMany("Restricoes")
                        .HasForeignKey("ItemDeProdutoID");
                });

            modelBuilder.Entity("Closify.Models.ValorNumerico", b =>
                {
                    b.HasOne("Closify.Models.Dimensao")
                        .WithMany("Altura")
                        .HasForeignKey("DimensaoID");

                    b.HasOne("Closify.Models.Dimensao")
                        .WithMany("Comprimento")
                        .HasForeignKey("DimensaoID1");

                    b.HasOne("Closify.Models.Dimensao")
                        .WithMany("Largura")
                        .HasForeignKey("DimensaoID2");
                });
#pragma warning restore 612, 618
        }
    }
}
